apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.core" . }}"
  labels: {{ include "harbor.labels" . | nindent 4 }}
data:
  app.conf: |+
    appname = Harbor
    runmode = dev
    enablegzip = true

    [dev]
    httpport = 8080