apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.core" . }}-envvars
  labels: {{ include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.harborAdminPassword }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.harborAdminPassword | b64enc | quote }}
  {{- else if (not .Values.forcePassword) }}
  HARBOR_ADMIN_PASSWORD: "{{ randAlphaNum 10 | b64enc }}"
  {{ else }}
  HARBOR_ADMIN_PASSWORD: {{ required "A Harbor Admin Password is required!" .Values.harborAdminPassword }}
  {{- end }}
  POSTGRESQL_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
  {{- if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ template "harbor.database.encryptedPassword" . }}
  {{- end }}