apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: {{ include "jenkins.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.jenkinsPassword }}
  jenkins-password: {{ default "" .Values.jenkinsPassword | b64enc | quote }}
  {{ else }}
  jenkins-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
