{{- if .Values.notary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "harbor.notary-server" . }}"
  labels: {{ include "harbor.labels" . | nindent 4 }}
    component: notary-server
spec:
  replicas: {{ .Values.notary.server.replicas }}
  selector:
    matchLabels: {{ include "harbor.matchLabels" . | nindent 6 }}
      component: notary-server
  template:
    metadata:
      labels: {{ include "harbor.labels" . | nindent 8 }}
        component: notary-server
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/notary/notary-cm.yaml") . | sha256sum }}
        checksum/secret-core: {{ include (print $.Template.BasePath "/core/core-secret.yaml") . | sha256sum }}
        {{- if .Values.notary.podAnnotations }}
        {{ toYaml .Values.notary.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
{{- include "harbor.imagePullSecrets" . | indent 6 }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
      - name: notary-server
        image: "{{ template "harbor.notaryServerImage" . }}"
        imagePullPolicy: {{ .Values.notaryServerImage.pullPolicy }}
        {{- if .Values.notary.server.resources }}
        resources: {{ toYaml .Values.notary.server.resources | nindent 10 }}
        {{- end }}
        env:
        - name: BITNAMI_DEBUG
          value: {{ ternary "true" "false" .Values.notaryServerImage.debug | quote }}
        - name: MIGRATIONS_PATH
          value: migrations/server/postgresql
        - name: DB_URL
          value: "{{ template "harbor.database.notaryServer" . }}"
        volumeMounts:
        - name: notary-config
          mountPath: /etc/notary
        - name: root-certificate
          mountPath: /root.crt
          subPath: tls.crt
        {{- if .Values.notary.secretName }}
        - name: notary-ca
          mountPath: /etc/ssl/notary/cert/notary-signer-ca.crt
          subPath: ca
        {{- end }}
        ports:
        - containerPort: 4443
          name: notary-server
      volumes:
      - name: notary-config
        configMap:
          name: "{{ template "harbor.notary-server" . }}"
      - name: root-certificate
        secret:
          {{- if .Values.core.secretName }}
          secretName: {{ .Values.core.secretName }}
          {{- else }}
          secretName: "{{ template "harbor.core" . }}"
          {{- end }}
      {{- if .Values.notary.secretName }}
      - name: notary-ca
        secret:
          secretName: {{ .Values.notary.secretName }}
      {{- end }}
    {{- with .Values.notary.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.notary.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.notary.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
