apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    release: "{{ .Release.Name }}"
