{{- if not .Values.security.passwordsSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    helm.sh/chart: {{ include "spark.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if eq (.Values.security.rpc.authenticationEnabled | quote ) "yes" }}
  rpc-authentication-secret: {{ "RPCDefaultSecret" | b64enc | quote }}
{{- end }}
{{- if eq (.Values.security.ssl.enabled | quote ) "yes" }}
  ssl-key-password: {{ randAlphaNum 10 | b64enc | quote }}
  ssl-keystore-password: {{ randAlphaNum 10 | b64enc | quote }}
  ssl-truststore-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
{{- end }}
