{{- if .Values.clair.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.clair" . }}"
  labels: {{ include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: clair
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
  selector:
    {{ include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: clair
{{- end }}
