apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorflow-resnet.fullname" . }}
  labels:
    app: {{ template "tensorflow-resnet.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: tf-serving
    port: {{ .Values.server.port }}
    targetPort: tf-serving
  - name: tf-serving-api
    port: {{ .Values.server.restApiPort }}
    targetPort: tf-serving-api
  selector:
    app: {{ template "tensorflow-resnet.name" . }}
