{{- if .Files.Glob "files/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxnet.fullname" . }}-files
  labels:
    app.kubernetes.io/name: {{ include "mxnet.name" . }}
    helm.sh/chart: {{ include "mxnet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
{{- end }}
