{{- if eq .Values.mode "distributed" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mxnet.fullname" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "mxnet.name" . }}
    helm.sh/chart: {{ include "mxnet.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mxnet.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mxnet.name" . }}
        helm.sh/chart: {{ include "mxnet.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/component: scheduler
    spec:
      {{- include "mxnet.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if .Values.cloneFilesFromGit.enabled }}
      initContainers:
      - name: git-clone-repository
        image: {{ include "git.image" . }}
        imagePullPolicy: {{ .Values.git.pullPolicy | quote }}
        command:
        - /bin/sh
        - -c
        - |
          git clone {{ .Values.cloneFilesFromGit.repository }} --branch {{ .Values.cloneFilesFromGit.revision }} /app
        volumeMounts:
        - name: git-cloned-files
          mountPath: /app
      {{- end }}
      {{- if .Values.initContainers }}
        {{- toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
      containers:
      - name: mxnet
        workingDir: {{ .Values.entrypoint.workDir }}
        image: {{ include "mxnet.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: 
        - bash
        - -c
        - |
        {{- include "mxnet.entrypoint" . | nindent 10 }}
        env:
        - name: DMLC_ROLE
          value: "scheduler"
        - name: DMLC_NUM_WORKER
          value: {{ .Values.workerCount | quote }}
        - name: DMLC_NUM_SERVER
          value: {{ .Values.serverCount | quote }}
        - name: DMLC_PS_ROOT_URI
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DMLC_PS_ROOT_PORT
          value: {{ .Values.schedulerPort | quote }}
      {{- if .Values.commonExtraEnvVars }}
        {{- include "mxnet.parseEnvVars" .Values.commonExtraEnvVars | nindent 8 }}
      {{- end }} 
      {{- if .Values.schedulerExtraEnvVars }}
        {{- include "mxnet.parseEnvVars" .Values.schedulerExtraVars | nindent 8 }}
      {{- end }}
        ports:
        - name: mxnet
          containerPort: {{ .Values.schedulerPort }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.schedulerPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.schedulerPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources: {{ toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.configMap }}
        - name: ext-files
          mountPath: /app
        {{- else if .Files.Glob "files/*" }}
        - name: local-files
          mountPath: /app
        {{- else if .Values.cloneFilesFromGit.enabled }}
        - name: git-cloned-files
          mountPath: /app
        {{- end }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- if .Values.existingSecret }}
        - name: secret-data
          mountPath: /secrets
        {{- end }}
    {{- if .Values.sidecars }}
      {{- toYaml .Values.sidecars | nindent 6 }}
    {{- end }}
      volumes:
      {{- if .Values.existingSecret }}
      - name: secret-data
        secret:
          secretName: {{ .Values.existingSecret }}
      {{- end }}
      {{- if .Values.configMap }}
      - name: ext-files
        configMap:
          name: {{ .Values.configMap }}
      {{- else if .Files.Glob "files/*" }}
      - name: local-files
        configMap:
          name: {{ include "mxnet.fullname" . }}-files
      {{- else if .Values.cloneFilesFromGit.enabled }}
      - name: git-cloned-files
        emptyDir: {}
      {{- end }}
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "mxnet.fullname" . }}-scheduler
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}
