{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) (eq .Values.mode "standalone") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "minio.name" . }}
    helm.sh/chart: {{ include "minio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "minio.storageClass" . }}
{{- end }}
