apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb-galera.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "mariadb-galera.name" . }}
    helm.sh/chart: {{ include "mariadb-galera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: galera
    port: 4567
    targetPort: galera
  - name: ist
    port: 4568
    targetPort: ist
  - name: sst
    port: 4444
    targetPort: sst
  selector:
    app.kubernetes.io/name: {{ include "mariadb-galera.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
