{{- if and .Values.serviceAccount.create .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "mariadb-galera.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb-galera.name" . }}
    helm.sh/chart: {{ include "mariadb-galera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
{{- end }}
