apiVersion: v1
kind: Secret
metadata:
  name: {{ template "wildfly.fullname" . }}
  labels:
    app: {{ template "wildfly.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.wildflyPassword }}
  wildfly-password: {{ default "" .Values.wildflyPassword | b64enc | quote }}
  {{ else }}
  wildfly-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
